### ISSUE TITLE
Compatibility with StatsBase and JuliaDB

### ISSUE THREAD

**Issue by xinkai-zhou** [OpenMendel/WiSER.jl#16]
ERROR: Unsatisfiable requirements detected for package StatsBase [2913bbd2]:
 StatsBase [2913bbd2] log:
 ├─possible versions are: 0.24.0-0.33.10 or uninstalled
 ├─restricted by compatibility requirements with WiSER [2ff19380] to versions: 0.33.0-0.33.10
 │ └─WiSER [2ff19380] log:
 │   ├─possible versions are: 0.1.2 or uninstalled
 └─restricted by compatibility requirements with JuliaDB [a93385a2] to versions: 0.24.0-0.32.2 — no versions left
   └─JuliaDB [a93385a2] log:
     ├─possible versions are: 0.9.0-0.13.1 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions 0.9.0-0.13.1

Would it be possible to allow for lower versions of StatsBase?

**Comment by kose-y** [comment]
Do you have a particular reason to use JuliaDB and WiSER in the same project?

**Comment by kose-y** [comment]
Closing this issue, as JuliaDB now supports StatsBase@0.33.
